version: '3'
services:
  db:
    image: mariadb:10.2
    container_name: gaoio-db
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  redis:
    image: redis:alpine
    container_name: gaoio-redis

  nginx:
    image: nginx:stable-alpine
    container_name: gaoio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./log/nginx:/var/log/nginx/:rw


